# Generated by Django 5.0.7 on 2024-07-18 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="WeatherQuery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("city", models.CharField(max_length=100)),
                ("query_count", models.IntegerField(default=1)),
                ("last_queried", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
